# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: whkb_pro2
    shield: hhkb_pro2
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: hhkb_pro2 custom_pro2
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: hhkb_pro2 custom_pro2
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME='"HG Ti"'
    artifact-name: hhkb_pro2_hg_ti
  - board: nice_nano_v2
    shield: hhkb_pro2 custom_pro2
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME='"HG Steel"'
    artifact-name: hhkb_pro2_hg_steel
  - board: nice_nano_v2
    shield: hhkb_pro2 custom_pro2
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME='"Sho60 v2"'
    artifact-name: hhkb_pro2_Sho60v2
